version: 2.1

references:
  environment: &environment
    IMAGE_NAME: "zappi/fsfreeze"

jobs:
  test:
    docker:
      - image: docker:18.06.3-ce-git
    environment: *environment
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - run:
          name: "Build Image"
          command: docker build -t $IMAGE_NAME .
      - run:
          name: "Test Image"
          command: docker run $IMAGE_NAME fsfreeze --version

workflows:
  build_test:
    jobs:
      - test
